# Generated by Django 2.2.3 on 2019-08-06 21:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20190806_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(default='1', validators=[django.core.validators.MinLengthValidator(1)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='draft',
            field=models.BooleanField(default=False),
        ),
    ]
